# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ginkgo/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    device/xiaomi/syberia

PRODUCT_PACKAGES += \
    ims
